# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import renderer_pb2 as renderer__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in renderer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RayTracerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/raytracer.RayTracer/LoadModel',
                request_serializer=renderer__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=renderer__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.RenderFrame = channel.unary_unary(
                '/raytracer.RayTracer/RenderFrame',
                request_serializer=renderer__pb2.RenderRequest.SerializeToString,
                response_deserializer=renderer__pb2.RenderResponse.FromString,
                _registered_method=True)


class RayTracerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModel(self, request, context):
        """Загрузка модели на сервер
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderFrame(self, request, context):
        """Рендеринг с заданными параметрами камеры
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RayTracerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=renderer__pb2.LoadModelRequest.FromString,
                    response_serializer=renderer__pb2.LoadModelResponse.SerializeToString,
            ),
            'RenderFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderFrame,
                    request_deserializer=renderer__pb2.RenderRequest.FromString,
                    response_serializer=renderer__pb2.RenderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raytracer.RayTracer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raytracer.RayTracer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RayTracer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raytracer.RayTracer/LoadModel',
            renderer__pb2.LoadModelRequest.SerializeToString,
            renderer__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raytracer.RayTracer/RenderFrame',
            renderer__pb2.RenderRequest.SerializeToString,
            renderer__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
