# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'renderer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erenderer.proto\x12\traytracer\":\n\x10LoadModelRequest\x12\x12\n\nmodel_data\x18\x01 \x01(\x0c\x12\x12\n\nmodel_path\x18\x02 \x01(\t\"5\n\x11LoadModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Y\n\x0c\x43\x61meraParams\x12\x10\n\x08position\x18\x01 \x03(\x02\x12\x0f\n\x07\x66orward\x18\x02 \x03(\x02\x12\r\n\x05right\x18\x03 \x03(\x02\x12\n\n\x02up\x18\x04 \x03(\x02\x12\x0b\n\x03\x66ov\x18\x05 \x01(\x02\"l\n\rRenderRequest\x12\'\n\x06\x63\x61mera\x18\x01 \x01(\x0b\x32\x17.raytracer.CameraParams\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x13\n\x0bmax_bounces\x18\x04 \x01(\x05\"e\n\x0eRenderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x32\x97\x01\n\tRayTracer\x12\x46\n\tLoadModel\x12\x1b.raytracer.LoadModelRequest\x1a\x1c.raytracer.LoadModelResponse\x12\x42\n\x0bRenderFrame\x12\x18.raytracer.RenderRequest\x1a\x19.raytracer.RenderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'renderer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMODELREQUEST']._serialized_start=29
  _globals['_LOADMODELREQUEST']._serialized_end=87
  _globals['_LOADMODELRESPONSE']._serialized_start=89
  _globals['_LOADMODELRESPONSE']._serialized_end=142
  _globals['_CAMERAPARAMS']._serialized_start=144
  _globals['_CAMERAPARAMS']._serialized_end=233
  _globals['_RENDERREQUEST']._serialized_start=235
  _globals['_RENDERREQUEST']._serialized_end=343
  _globals['_RENDERRESPONSE']._serialized_start=345
  _globals['_RENDERRESPONSE']._serialized_end=446
  _globals['_RAYTRACER']._serialized_start=449
  _globals['_RAYTRACER']._serialized_end=600
# @@protoc_insertion_point(module_scope)
